<pre><code></code></pre>
<p><br />
</p>
<link rel='stylesheet' href='../style.css'>
<script src='../script.js'></script>
<h1>NAME</h1>
<p>Try::Tiny - Minimal try/catch with proper preservation of $@</p>
<h1>VERSION</h1>
<p>version 0.31</p>
<h1>SYNOPSIS</h1>
<p>You can use Try::Tiny's <code>try</code> and <code>catch</code> to
expect and handle exceptional conditions, avoiding quirks in Perl and
common mistakes:</p>
<p># handle errors with a catch handler try { die "foo"; } catch { warn
"caught error: $_"; # not $@ };</p>
<p>You can also use it like a standalone <code>eval</code> to catch and
ignore any error conditions. Obviously, this is an extreme measure not
to be undertaken lightly:</p>
<p># just silence errors try { die "foo"; };</p>
<h1>DESCRIPTION</h1>
<p>This module provides bare bones
<code>try</code>/<code>catch</code>/<code>finally</code> statements that
are designed to minimize common mistakes with eval blocks, and NOTHING
else.</p>
<p>This is unlike TryCatch which provides a nice syntax and avoids
adding another call stack layer, and supports calling
<code>return</code> from the <code>try</code> block to return from the
parent subroutine. These extra features come at a cost of a few
dependencies, namely Devel::Declare and Scope::Upper which are
occasionally problematic, and the additional catch filtering uses Moose
type constraints which may not be desirable either.</p>
<p>The main focus of this module is to provide simple and reliable error
handling for those having a hard time installing TryCatch, but who still
want to write correct <code>eval</code> blocks without 5 lines of
boilerplate each time.</p>
<p>It's designed to work as correctly as possible in light of the
various pathological edge cases (see BACKGROUND) and to be compatible
with any style of error values (simple strings, references, objects,
overloaded objects, etc).</p>
<p>If the <code>try</code> block dies, it returns the value of the last
statement executed in the <code>catch</code> block, if there is one.
Otherwise, it returns <code>undef</code> in scalar context or the empty
list in list context. The following examples all assign
<code>"bar"</code> to <code>$x</code>:</p>
<p>my $x = try { die "foo" } catch { "bar" }; my $x = try { die "foo" }
|| "bar"; my $x = (try { die "foo" }) // "bar"; my $x = eval { die "foo"
} || "bar";</p>
<p>You can add <code>finally</code> blocks, yielding the following:</p>
<p>my $x; try { die foo } finally { $x = bar }; try { die foo } catch {
warn "Got a die: $_" } finally { $x = bar };</p>
<p><code>finally</code> blocks are always executed making them suitable
for cleanup code which cannot be handled using local. You can add as
many <code>finally</code> blocks to a given <code>try</code> block as
you like.</p>
<p>Note that adding a <code>finally</code> block without a preceding
<code>catch</code> block suppresses any errors. This behaviour is
consistent with using a standalone <code>eval</code>, but it is not
consistent with <code>try</code>/<code>finally</code> patterns found in
other programming languages, such as Java, Python, Javascript or C#. If
you learned the <code>try</code>/<code>finally</code> pattern from one
of these languages, watch out for this.</p>
<h1>EXPORTS</h1>
<p>All functions are exported by default using Exporter.</p>
<p>If you need to rename the <code>try</code>, <code>catch</code> or
<code>finally</code> keyword consider using Sub::Import to get
Sub::Exporter's flexibility.</p>
<dl>
<dt>try (&amp;;@)</dt>
<dd>
<p>Takes one mandatory <code>try</code> subroutine, an optional
<code>catch</code> subroutine and <code>finally</code> subroutine. The
mandatory subroutine is evaluated in the context of an <code>eval</code>
block. If no error occurred the value from the first block is returned,
preserving list/scalar context. If there was an error and the second
subroutine was given it will be invoked with the error in
<code>$_</code> (localized) and as that block's first and only argument.
<code>$@</code> does <strong>not</strong> contain the error. Inside the
<code>catch</code> block it has the same value it had before the
<code>try</code> block was executed. Note that the error may be false,
but if that happens the <code>catch</code> block will still be invoked.
Once all execution is finished then the <code>finally</code> block, if
given, will execute.</p>
</dd>
<dt>catch (&amp;;@)</dt>
<dd>
<p>Intended to be used in the second argument position of
<code>try</code>. Returns a reference to the subroutine it was given but
blessed as <code>Try::Tiny::Catch</code> which allows try to decode
correctly what to do with this code reference. catch { ... } Inside the
<code>catch</code> block the caught error is stored in <code>$_</code>,
while previous value of <code>$@</code> is still available for use. This
value may or may not be meaningful depending on what happened before the
<code>try</code>, but it might be a good idea to preserve it in an error
stack. For code that captures <code>$@</code> when throwing new errors
(i.e. Class::Throwable), you'll need to do: local $@ = $_;</p>
</dd>
<dt>finally (&amp;;@)</dt>
<dd>
<p> try { ... } catch { ... } finally { ... }; Or try { ... } finally {
... }; Or even try { ... } finally { ... } catch { ... }; Intended to be
the second or third element of <code>try</code>. <code>finally</code>
blocks are always executed in the event of a successful <code>try</code>
or if <code>catch</code> is run. This allows you to locate cleanup code
which cannot be done via <code>local()</code> e.g. closing a file
handle. When invoked, the <code>finally</code> block is passed the error
that was caught. If no error was caught, it is passed nothing. (Note
that the <code>finally</code> block does not localize <code>$_</code>
with the error, since unlike in a <code>catch</code> block, there is no
way to know if <code>$_ == undef</code> implies that there were no
errors.) In other words, the following code does just what you would
expect: try { die_sometimes(); } catch { # ...code run in case of error
} finally { if (@_) { print "The try block died with: @_\n"; } else {
print "The try block ran without error.\n"; } }; <strong>You must always
do your own error handling in the <code>finally</code> block</strong>.
<code>Try::Tiny</code> will not do anything about handling possible
errors coming from code located in these blocks. Furthermore
<strong>exceptions in <code>finally</code> blocks are not trappable and
are unable</strong> to influence the execution of your program. This is
due to limitation of <code>DESTROY</code>-based scope guards, which
<code>finally</code> is implemented on top of. This may change in a
future version of Try::Tiny. In the same way <code>catch()</code>
blesses the code reference this subroutine does the same except it bless
them as <code>Try::Tiny::Finally</code>.</p>
</dd>
</dl>
<h1>BACKGROUND</h1>
<p>There are a number of issues with <code>eval</code>.</p>
<h2>Clobbering $@</h2>
<p>When you run an <code>eval</code> block and it succeeds,
<code>$@</code> will be cleared, potentially clobbering an error that is
currently being caught.</p>
<p>This causes action at a distance, clearing previous errors your
caller may have not yet handled.</p>
<p><code>$@</code> must be properly localized before invoking
<code>eval</code> in order to avoid this issue.</p>
<p>More specifically, before Perl version 5.14.0 <code>$@</code> was
clobbered at the beginning of the <code>eval</code>, which also made it
impossible to capture the previous error before you die (for instance
when making exception objects with error stacks).</p>
<p>For this reason <code>try</code> will actually set <code>$@</code> to
its previous value (the one available before entering the
<code>try</code> block) in the beginning of the <code>eval</code>
block.</p>
<h2>Localizing $@ silently masks errors</h2>
<p>Inside an <code>eval</code> block, <code>die</code> behaves sort of
like:</p>
<p>sub die { $@ = $_[0]; return_undef_from_eval(); }</p>
<p>This means that if you were polite and localized <code>$@</code> you
can't die in that scope, or your error will be discarded (printing
Something's wrong instead).</p>
<p>The workaround is very ugly:</p>
<p>my $error = do { local $@; eval { ... }; $@; }; ... die $error;</p>
<h2>$@ might not be a true value</h2>
<p>This code is wrong:</p>
<p>if ( $@ ) { ... }</p>
<p>because due to the previous caveats it may have been unset.</p>
<p><code>$@</code> could also be an overloaded error object that
evaluates to false, but that's asking for trouble anyway.</p>
<p>The classic failure mode (fixed in Perl 5.14.0) is:</p>
<p>sub Object::DESTROY { eval { ... } } eval { my $obj = Object-&gt;new;
die "foo"; }; if ( $@ ) { }</p>
<p>In this case since <code>Object::DESTROY</code> is not localizing
<code>$@</code> but still uses <code>eval</code>, it will set
<code>$@</code> to <code>""</code>.</p>
<p>The destructor is called when the stack is unwound, after
<code>die</code> sets <code>$@</code> to
<code>"foo at Foo.pm line 42\n"</code>, so by the time
<code>if ( $@ )</code> is evaluated it has been cleared by
<code>eval</code> in the destructor.</p>
<p>The workaround for this is even uglier than the previous ones. Even
though we can't save the value of <code>$@</code> from code that doesn't
localize, we can at least be sure the <code>eval</code> was aborted due
to an error:</p>
<p>my $failed = not eval { ... return 1; };</p>
<p>This is because an <code>eval</code> that caught a <code>die</code>
will always return a false value.</p>
<h1>ALTERNATE SYNTAX</h1>
<p>Using Perl 5.10 you can use Switch statements in perlsyn (but please
don't, because that syntax has since been deprecated because there was
too much unexpected magical behaviour).</p>
<p>The <code>catch</code> block is invoked in a topicalizer context
(like a <code>given</code> block), but note that you can't return a
useful value from <code>catch</code> using the <code>when</code> blocks
without an explicit <code>return</code>.</p>
<p>This is somewhat similar to Perl 6's <code>CATCH</code> blocks. You
can use it to concisely match errors:</p>
<p>try { require Foo; } catch { when (/^Cant locate .*?\.pm in \@INC/) {
} # ignore default { die $_ } };</p>
<h1>CAVEATS</h1>
<ul>
<li><p><code>@_</code> is not available within the <code>try</code>
block, so you need to copy your argument list. In case you want to work
with argument values directly via <code>@_</code> aliasing (i.e. allow
<code>$_[1] = "foo"</code>), you need to pass <code>@_</code> by
reference: sub foo { my ( $self, @args ) = @_; try {
$self-&gt;bar(@args) } } or sub bar_in_place { my $self = shift; my
$args = \@_; try { $_ = $self-&gt;bar($_) for @$args } }</p></li>
<li><p><code>return</code> returns from the <code>try</code> block, not
from the parent sub (note that this is also how <code>eval</code> works,
but not how TryCatch works): sub parent_sub { try { die; } catch {
return; }; say "this text WILL be displayed, even though an exception is
thrown"; } Instead, you should capture the return value: sub parent_sub
{ my $success = try { die; 1; }; return unless $success; say "This text
WILL NEVER appear!"; } # OR sub parent_sub_with_catch { my $success =
try { die; 1; } catch { # do something with $_ return undef; #see note
}; return unless $success; say "This text WILL NEVER appear!"; } Note
that if you have a <code>catch</code> block, it must return
<code>undef</code> for this to work, since if a <code>catch</code> block
exists, its return value is returned in place of <code>undef</code> when
an exception is thrown.</p></li>
<li><p><code>try</code> introduces another caller stack frame.
Sub::Uplevel is not used. Carp will not report this when using full
stack traces, though, because <code>%Carp::Internal</code> is used. This
lack of magic is considered a feature.</p></li>
<li><p>The value of <code>$_</code> in the <code>catch</code> block is
not guaranteed to be the value of the exception thrown (<code>$@</code>)
in the <code>try</code> block. There is no safe way to ensure this,
since <code>eval</code> may be used unhygienically in destructors. The
only guarantee is that the <code>catch</code> will be called if an
exception is thrown.</p></li>
<li><p>The return value of the <code>catch</code> block is not ignored,
so if testing the result of the expression for truth on success, be sure
to return a false value from the <code>catch</code> block: my $obj = try
{ MightFail-&gt;new; } catch { ... return; # avoid returning a true
value; }; return unless $obj;</p></li>
<li><p><code>$SIG{_ _DIE_ _}</code> is still in effect. Though it can be
argued that <code>$SIG{_ _DIE_ _}</code> should be disabled inside of
<code>eval</code> blocks, since it isn't people have grown to rely on
it. Therefore in the interests of compatibility, <code>try</code> does
not disable <code>$SIG{_ _DIE_ _}</code> for the scope of the error
throwing code.</p></li>
<li><p>Lexical <code>$_</code> may override the one set by
<code>catch</code>. For example Perl 5.10's <code>given</code> form uses
a lexical <code>$_</code>, creating some confusing behavior: given
($foo) { when (...) { try { ... } catch { warn $_; # will print $foo,
not the error warn $_[0]; # instead, get the error like this } } } Note
that this behavior was changed once again in Perl5 version 18
&lt;https://metacpan.org/module/perldelta#given-now-aliases-the-global-_&gt;.
However, since the entirety of lexical <code>$_</code> is now considered
experimental
&lt;https://metacpan.org/module/perldelta#Lexical-_-is-now-experimental&gt;,
it is unclear whether the new version 18 behavior is final.</p></li>
</ul>
<h1>SEE ALSO</h1>
<dl>
<dt>Syntax::Keyword::Try</dt>
<dd>
<p>Only available on perls &gt;= 5.14, with a slightly different syntax
(e.g. no trailing <code>;</code> because it's actually a keyword, not a
sub, but this means you can <code>return</code> and <code>next</code>
within it). Use Feature::Compat::Try to automatically switch to the
native <code>try</code> syntax in newer perls (when available). See also
Try Catch Exception Handling.</p>
</dd>
<dt>TryCatch</dt>
<dd>
<p>Much more feature complete, more convenient semantics, but at the
cost of implementation complexity.</p>
</dd>
<dt>autodie</dt>
<dd>
<p>Automatic error throwing for builtin functions and more. Also
designed to work well with <code>given</code>/<code>when</code>.</p>
</dd>
<dt>Throwable</dt>
<dd>
<p>A lightweight role for rolling your own exception classes.</p>
</dd>
<dt>Error</dt>
<dd>
<p>Exception object implementation with a <code>try</code> statement.
Does not localize <code>$@</code>.</p>
</dd>
<dt>Exception::Class::TryCatch</dt>
<dd>
<p>Provides a <code>catch</code> statement, but properly calling
<code>eval</code> is your responsibility. The <code>try</code> keyword
pushes <code>$@</code> onto an error stack, avoiding some of the issues
with <code>$@</code>, but you still need to localize to prevent
clobbering.</p>
</dd>
</dl>
<h1>LIGHTNING TALK</h1>
<p>I gave a lightning talk about this module, you can see the slides
(Firefox only):</p>
<p>&lt;http://web.archive.org/web/20100628040134/http://nothingmuch.woobling.org/talks/takahashi.xul&gt;</p>
<p>Or read the source:</p>
<p>&lt;http://web.archive.org/web/20100305133605/http://nothingmuch.woobling.org/talks/yapc_asia_2009/try_tiny.yml&gt;</p>
<h1>SUPPORT</h1>
<p>Bugs may be submitted through the RT bug tracker
&lt;https://rt.cpan.org/Public/Dist/Display.html?Name=Try-Tiny&gt; (or
bug-Try-Tiny@rt.cpan.org &lt;mailto:bug-Try-Tiny@rt.cpan.org&gt;).</p>
<h1>AUTHORS</h1>
<ul>
<li><p>יובל קוג'מן (Yuval Kogman)
&lt;nothingmuch@woobling.org&gt;</p></li>
<li><p>Jesse Luehrs &lt;doy@tozt.net&gt;</p></li>
</ul>
<h1>CONTRIBUTORS</h1>
<ul>
<li><p>Karen Etheridge &lt;ether@cpan.org&gt;</p></li>
<li><p>Peter Rabbitson &lt;ribasushi@cpan.org&gt;</p></li>
<li><p>Ricardo Signes &lt;rjbs@cpan.org&gt;</p></li>
<li><p>Mark Fowler &lt;mark@twoshortplanks.com&gt;</p></li>
<li><p>Graham Knop &lt;haarg@haarg.org&gt;</p></li>
<li><p>Aristotle Pagaltzis &lt;pagaltzis@gmx.de&gt;</p></li>
<li><p>Dagfinn Ilmari Mannsåker &lt;ilmari@ilmari.org&gt;</p></li>
<li><p>Lukas Mai &lt;l.mai@web.de&gt;</p></li>
<li><p>Alex &lt;alex@koban.(none)&gt;</p></li>
<li><p>anaxagoras &lt;walkeraj@gmail.com&gt;</p></li>
<li><p>Andrew Yates &lt;ayates@haddock.local&gt;</p></li>
<li><p>awalker &lt;awalker@sourcefire.com&gt;</p></li>
<li><p>chromatic &lt;chromatic@wgz.org&gt;</p></li>
<li><p>cm-perl &lt;cm-perl@users.noreply.github.com&gt;</p></li>
<li><p>David Lowe &lt;davidl@lokku.com&gt;</p></li>
<li><p>Glenn Fowler &lt;cebjyre@cpan.org&gt;</p></li>
<li><p>Hans Dieter Pearcey &lt;hdp@weftsoar.net&gt;</p></li>
<li><p>Jens Berthold &lt;jens@jebecs.de&gt;</p></li>
<li><p>Jonathan Yu &lt;JAWNSY@cpan.org&gt;</p></li>
<li><p>Marc Mims &lt;marc@questright.com&gt;</p></li>
<li><p>Mark Stosberg &lt;mark@stosberg.com&gt;</p></li>
<li><p>Pali &lt;pali@cpan.org&gt;</p></li>
<li><p>Paul Howarth &lt;paul@city-fan.org&gt;</p></li>
<li><p>Rudolf Leermakers &lt;rudolf@hatsuseno.org&gt;</p></li>
</ul>
<h1>COPYRIGHT AND LICENCE</h1>
<p>This software is Copyright (c) 2009 by יובל קוג'מן (Yuval
Kogman).</p>
<p>This is free software, licensed under:</p>
<p>The MIT (X11) License</p>
